## This playbook deploys the whole application stack in this site.
---
- name: Apply common configuration to all hosts
  hosts: all
  become: yes
  roles:
    - common

- name: Configure and deploy database servers.
  hosts: tag_Group_dbservers
  become: yes
  roles:
    - db
  tags:
    - db

# Note that we include two roles here,
# the 'base-apache' role which simply sets up Apache, and 'web' which includes
# our example web application.
- name: Configure and deploy the web servers.
  hosts: tag_Group_webservers
  become: yes
  roles:
    - base-apache
    - web
  tags:
    - web

- name: Configure and deploy the load balancer(s).
  hosts: tag_Group_lbservers
  become: yes
  roles:
    - haproxy
  tags:
    - lb

- name: Configure and deploy the Nagios monitoring node(s).
  hosts: tag_Group_monitoring
  become: yes
  roles:
    - base-apache
    - nagios
  tags:
    - monitoring
