## This playbook deploys the whole application stack in this site.
---
- name: Apply common configuration to all hosts
  hosts: all
  roles:
    - common

- name: Configure and deploy database servers.
  hosts: type_db
  roles:
    - db
  tags:
    - db

# Note that we include two roles here,
# the 'base-apache' role which simply sets up Apache, and 'web' which includes
# our example web application.
- name: Configure and deploy the web servers.
  hosts: type_web
  roles:
    - base-apache
    - web

  tags:
    - web

- name: Configure and deploy the load balancer(s).
  hosts: type_lb
  roles:
    - haproxy
  tags:
    - lb

- name: Configure and deploy the Nagios monitoring node(s).
  hosts: monitoring
  roles:
    - base-apache
    - nagios
  tags:
    - monitoring
