---
- name: Install WordPress, MariaDB, Nginx, and PHP-FPM
  hosts: wordpress-server
  remote_user: devops
  become: yes

  roles:
    - common
    - mariadb
    - nginx
    - php-fpm
    - wordpress
