---
- name: Setup
  hosts: localhost
  connection: local
  gather_facts: no
  become: no
  tasks:
    - shell: whoami
      register: whoami

    - set_fact:
        demo_user: "{{ whoami.stdout }}"

    - set_fact:
        demo_user: "{{ tower_user_name }}"
      when: "{{ whoami.stdout == 'awx' }}"

- name: Deprovision demo EC2 instances for the current user
  hosts: tag_AnsibleDemo_True:&tag_Name_ansible_demo_{{ demo_user }}
  gather_facts: no
  become: no
  tasks:
    - name: Ensure demo EC2 instances are terminated
      ec2:
        region: "{{ aws_region }}"
        instance_ids: "{{ ec2_id }}"
        state: absent
      delegate_to: localhost
