---
- name: Install required packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - httpd
    - php
    - php-mysql
    - git

- name: http service state
  service:
    name: httpd
    state: started
    enabled: yes
