---
# This role will install MariaDB and create db user and give permissions.

- name: Install MariaDB package
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mariadb
    - mariadb-server
    - MySQL-python

- name: Start MariaDB Service
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Create MariaDB configuration file
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
  notify:
    - restart mariadb

- name: Create Application Database
  mysql_db:
    name: "{{ dbname }}"
    state: present

- name: Create Application DB User
  mysql_user:
    name: "{{ dbuser }}"
    password: "{{ upassword }}"
    priv: "*.*:ALL"
    host: "'%'"
    state: present
